version: "3.8"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: asterisk
      POSTGRES_PASSWORD: asteriskpw
      POSTGRES_DB: ari_logs
    volumes:
      - pgdata:/var/lib/postgresql/data

  asterisk:
    image: andrius/asterisk:latest
    ports:
      - "5060:5060/udp"
      - "8088:8088"
    volumes:
      - ./Asterisk/config:/etc/asterisk
      - ./Asterisk/recordings:/var/spool/asterisk/monitor
      - ./Asterisk/recordings:/var/spool/asterisk/recording
      - ./Asterisk/recordings:/var/lib/asterisk/sounds
    depends_on:
      - postgres

  ari-app:
    build:
      context: ./Asterisk/ari-app
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - asterisk
    volumes:
      - ./Asterisk/recordings:/var/spool/asterisk/monitor
      - ./Asterisk/recordings:/var/lib/asterisk/sounds
    env_file:
      - ./Asterisk/ari-app/.env
    environment:
      - RECORDINGS_DIR=/var/lib/asterisk/sounds

  rasa:
    image: rasa/rasa:3.6.10
    entrypoint: >
      sh -c "rasa train && rasa run --enable-api --cors '*' --debug"
    ports:
      - "5005:5005"
    volumes:
      - ./rasa:/app
      - ./rasa/models:/app/models
    working_dir: /app
    environment:
      - SQLALCHEMY_WARN_20=1
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
    restart: unless-stopped

  sipp:
    image: grigiu/sipp
    depends_on:
      - asterisk
      - ari-app
    volumes:
      - ./Asterisk/sipp:/sipp
    working_dir: /sipp
    entrypoint: ""
    command:
      - sh
      - -c
      - |
        sleep 15 &&
        while true; do
          sipp asterisk \
            -sf /sipp/auth-uac.xml \
            -inf /sipp/users.csv \
            -m 1 \
            -s 1001 \
            -ap 1001 \
            -au 1001 \
            -p 5062 \
            -t un
          sleep 5
        done

volumes:
  pgdata:
